---
title: "Homework6"
author: "Danny Nguyen"
date: "2023-11-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Question 1 

```{r}
homicide <- read_csv("homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    victim_age = as.numeric(victim_age),
    victim_race = fct(victim_race),
    result = ifelse(disposition == "Closed by arrest", 1, 0)) %>% 
  group_by(city_state)%>% 
  filter(city_state != "Tulsa,AL" & city_state!="Dallas,TX" & city_state != "Phoenix,AZ" & city_state!="Kansas City,MO")%>% 
  filter(victim_race == "White" | victim_race =="Black") %>%
  select(city_state, result, victim_age, victim_race, victim_sex)

baltimore = homicide %>% 
  filter(city_state == "Baltimore,MD")%>% 
  glm(result ~ victim_age + victim_sex + victim_race, data = ., family =binomial())%>%
  broom::tidy() %>%
  mutate(
    OR = exp(estimate),
    lower_ci = exp(estimate - 1.96 * std.error),
    upper_ci = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, estimate, OR, lower_ci,upper_ci ) %>% 
  knitr::kable(digits = 3)

baltimore
```

```{r}
OR = homicide %>% 
  nest(data = -city_state) %>% 
  mutate(
    regression = map(.x = data, ~glm(formula = result ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
    results = map(regression, broom::tidy)
  ) %>% 
  select(-data, -regression) %>% 
  unnest(results) %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
    OR = exp(estimate),
    lower_ci = exp(estimate - 1.96 * std.error),
    upper_ci = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state,OR, lower_ci,upper_ci ) 

OR
```

```{r}
OR %>% 
  ggplot(aes(x = fct_reorder(city_state, OR), y = OR)) +
  geom_point() + 
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(
    x = "City",
    y = "Adjusted OR",
    title = "Estimated ORs and CIs"
  )
```

